# Generated by Django 5.0.4 on 2024-04-17 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plans',
            table='plans',
        ),
    ]
