# Generated by Django 5.0.4 on 2024-04-17 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_plan_delete_plans'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
