# Generated by Django 5.0.4 on 2024-04-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing', '0004_delete_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
                ('price', models.FloatField()),
                ('duration', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'plans',
                'managed': False,
            },
        ),
    ]
