# Generated by Django 5.0.4 on 2024-04-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlansFeatures',
            fields=[
                ('plan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('features', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'plans_features',
                'managed': False,
            },
        ),
    ]
