# Generated by Django 5.0.4 on 2024-04-17 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_plansfeatures'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plansfeatures',
            options={},
        ),
    ]
