# Generated by Django 5.0.4 on 2024-04-17 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_alter_plansfeatures_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plans',
        ),
        migrations.AlterModelOptions(
            name='plansfeatures',
            options={'managed': False},
        ),
    ]
